# Use Node.js base image
FROM node:18-slim

# Set working directory
WORKDIR /app

# Copy frontend dist files
COPY clairvoyance-webapp/dist/ .

# Expose port - though this will only be used internally
EXPOSE 4321

# Command to run the Astro server
CMD ["node", "./server/entry.mjs"]