// Generated by pydantic-to-ts-converter
// From Pydantic models in Python module: models (path: models)
// Timestamp: 2025-09-27T00:51:46.911568


export type WithObjectId<T> = T & { _id: string };


export enum AlertCause {
  UNKNOWN_CAUSE = "UNKNOWN_CAUSE",
  OTHER_CAUSE = "OTHER_CAUSE",
  TECHNICAL_PROBLEM = "TECHNICAL_PROBLEM",
  STRIKE = "STRIKE",
  DEMONSTRATION = "DEMONSTRATION",
  ACCIDENT = "ACCIDENT",
  HOLIDAY = "HOLIDAY",
  WEATHER = "WEATHER",
  MAINTENANCE = "MAINTENANCE",
  CONSTRUCTION = "CONSTRUCTION",
  POLICE_ACTIVITY = "POLICE_ACTIVITY",
  MEDICAL_EMERGENCY = "MEDICAL_EMERGENCY",
}

export enum AlertEffect {
  NO_SERVICE = "NO_SERVICE",
  REDUCED_SERVICE = "REDUCED_SERVICE",
  SIGNIFICANT_DELAYS = "SIGNIFICANT_DELAYS",
  DETOUR = "DETOUR",
  ADDITIONAL_SERVICE = "ADDITIONAL_SERVICE",
  MODIFIED_SERVICE = "MODIFIED_SERVICE",
  OTHER_EFFECT = "OTHER_EFFECT",
  UNKNOWN_EFFECT = "UNKNOWN_EFFECT",
  STOP_MOVED = "STOP_MOVED",
  NO_EFFECT = "NO_EFFECT",
  ACCESSIBILITY_ISSUE = "ACCESSIBILITY_ISSUE",
}

export enum AlertSeverity {
  UNKNOWN_SEVERITY = "UNKNOWN_SEVERITY",
  INFO = "INFO",
  WARNING = "WARNING",
  SEVERE = "SEVERE",
}

export enum CalendarExceptionType {
  ADDED = "ADDED",
  REMOVED = "REMOVED",
}

export enum CongestionLevel {
  UNKNOWN_CONGESTION_LEVEL = "UNKNOWN_CONGESTION_LEVEL",
  RUNNING_SMOOTHLY = "RUNNING_SMOOTHLY",
  STOP_AND_GO = "STOP_AND_GO",
  CONGESTION = "CONGESTION",
  SEVERE_CONGESTION = "SEVERE_CONGESTION",
}

export enum Direction {
  OUTBOUND = "OUTBOUND",
  INBOUND = "INBOUND",
}

export enum LocationType {
  STOP_OR_PLATFORM = "STOP_OR_PLATFORM",
  STATION = "STATION",
  ENTRANCE_EXIT = "ENTRANCE_EXIT",
  GENERIC_NODE = "GENERIC_NODE",
  BOARDING_AREA = "BOARDING_AREA",
}

export enum OccupancyStatus {
  EMPTY = "EMPTY",
  MANY_SEATS_AVAILABLE = "MANY_SEATS_AVAILABLE",
  FEW_SEATS_AVAILABLE = "FEW_SEATS_AVAILABLE",
  STANDING_ROOM_ONLY = "STANDING_ROOM_ONLY",
  CRUSHED_STANDING_ROOM_ONLY = "CRUSHED_STANDING_ROOM_ONLY",
  FULL = "FULL",
  NOT_ACCEPTING_PASSENGERS = "NOT_ACCEPTING_PASSENGERS",
  NO_DATA_AVAILABLE = "NO_DATA_AVAILABLE",
  NOT_BOARDABLE = "NOT_BOARDABLE",
}

export enum PickupDropOff {
  REGULAR = "REGULAR",
  NO_PICKUP_OR_DROP_OFF = "NO_PICKUP_OR_DROP_OFF",
  PHONE_AGENCY = "PHONE_AGENCY",
  COORDINATE_WITH_DRIVER = "COORDINATE_WITH_DRIVER",
}

export enum RouteType {
  TRAM = "TRAM",
  SUBWAY = "SUBWAY",
  RAIL = "RAIL",
  BUS = "BUS",
  FERRY = "FERRY",
  CABLE_TRAM = "CABLE_TRAM",
  AERIAL_LIFT = "AERIAL_LIFT",
  FUNICULAR = "FUNICULAR",
  TROLLEYBUS = "TROLLEYBUS",
  MONORAIL = "MONORAIL",
}

export enum StopTimeUpdateScheduleRelationship {
  SCHEDULED = "SCHEDULED",
  SKIPPED = "SKIPPED",
  NO_DATA = "NO_DATA",
  UNSCHEDULED = "UNSCHEDULED",
}

export enum StrEnum {

}

export enum Timepoint {
  APPROXIMATE = "APPROXIMATE",
  EXACT = "EXACT",
}

export enum TripDescriptorScheduleRelationship {
  SCHEDULED = "SCHEDULED",
  ADDED = "ADDED",
  UNSCHEDULED = "UNSCHEDULED",
  CANCELED = "CANCELED",
  REPLACEMENT = "REPLACEMENT",
  DUPLICATED = "DUPLICATED",
  NEW = "NEW",
  DELETED = "DELETED",
}

export enum TripInstanceState {
  PRISTINE = "PRISTINE",
  DIRTY = "DIRTY",
  REMOVED = "REMOVED",
}

export enum VehicleStopStatus {
  INCOMING_AT = "INCOMING_AT",
  STOPPED_AT = "STOPPED_AT",
  IN_TRANSIT_TO = "IN_TRANSIT_TO",
}

export enum WheelchairBoarding {
  NO_INFO = "NO_INFO",
  ACCESSIBLE = "ACCESSIBLE",
  NOT_ACCESSIBLE = "NOT_ACCESSIBLE",
}

export interface Agency {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  source_agency_id: string;
  agency_name: string;
  agency_url: string;
  agency_timezone: string;
  agency_lang?: null | string;
  agency_phone?: null | string;
  agency_fare_url?: null | string;
  agency_email?: null | string;
}

export interface Alert {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  alert_id: number;
  cause?: AlertCause;
  effect?: AlertEffect;
  header_text?: null | string;
  description_text?: null | string;
  url?: null | string;
  severity_level?: AlertSeverity;
  starts_at?: Date | null;
  ends_at?: Date | null;
  alerted_entities?: AlertedEntity[];
  ingested_at?: Date;
}

export interface AlertedEntity {
  route_id?: null | string;
  route_type?: RouteType | null;
  direction_id?: Direction | null;
  stop_id?: null | string;
  trip_id?: null | string;
  start_time?: null | string;
  start_date?: null | string;
}

export interface CalendarDate {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  service_id: string;
  date: string;
  exception_type: CalendarExceptionType;
}

export interface Document {
  _id?: null | string;
  revision_id?: null | string;
}

export interface FeedInfo {
  _id?: null | string;
  revision_id?: null | string;
  feed_hash: string;
  agency_id: string;
  feed_publisher_name?: null | string;
  feed_publisher_url?: null | string;
  feed_lang?: null | string;
  feed_version?: null | string;
  feed_start_date?: null | string;
  feed_end_date?: null | string;
}

export interface LineStringGeometry {
  type?: string;
  coordinates: number[][];
}

export interface PointGeometry {
  type?: string;
  coordinates: number[];
}

export interface Route {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  route_id: string;
  route_short_name?: null | string;
  route_long_name?: null | string;
  route_type: RouteType;
  route_color?: null | string;
  route_text_color?: null | string;
}

export interface Shape {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  shape_id: string;
  geometry: LineStringGeometry;
  distances_traveled?: null | number[];
}

export interface Stop {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  stop_id: string;
  stop_code?: null | string;
  stop_name?: null | string;
  stop_desc?: null | string;
  location?: PointGeometry | null;
  zone_id?: null | string;
  stop_url?: null | string;
  location_type?: LocationType | null;
  parent_station?: null | string;
  stop_timezone?: null | string;
  wheelchair_boarding?: WheelchairBoarding | null;
}

export interface StopTime {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  trip_id: string;
  arrival_time: string;
  departure_time: string;
  stop_id?: null | string;
  stop_sequence: number;
  stop_headsign?: null | string;
  pickup_type?: PickupDropOff | null;
  drop_off_type?: PickupDropOff | null;
  timepoint: Timepoint;
  shape_dist_traveled?: null | number;
}

export interface StopTimeInstance {
  stop_id: string;
  stop_headsign?: null | string;
  pickup_type?: PickupDropOff | null;
  drop_off_type?: PickupDropOff | null;
  timepoint: Timepoint;
  shape_dist_traveled?: null | number;
  arrival_datetime?: Date | null;
  departure_datetime?: Date | null;
  predicted_arrival_datetime?: Date | null;
  predicted_departure_datetime?: Date | null;
  predicted_arrival_uncertainty?: null | number;
  predicted_departure_uncertainty?: null | number;
  schedule_relationship?: StopTimeUpdateScheduleRelationship | null;
}

export interface Trip {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  trip_id: string;
  route_id: string;
  service_id: string;
  trip_headsign?: null | string;
  trip_short_name?: null | string;
  direction_id?: Direction | null;
  block_id?: null | string;
  shape_id?: null | string;
}

export interface TripDescriptor {
  trip_id?: null | string;
  start_time?: null | string;
  start_date?: null | string;
  route_id?: null | string;
  direction_id?: Direction | null;
  schedule_relationship?: TripDescriptorScheduleRelationship | null;
}

export interface TripInstance {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  trip_id: string;
  start_date: string;
  start_time: string;
  route_id: string;
  direction_id?: Direction | null;
  state?: TripInstanceState;
  start_datetime: Date;
  stop_times: StopTimeInstance[];
  trip: any;
  route: any;
  shape?: any | null;
  vehicle?: any | null;
  positions?: any[];
}

export interface Vehicle {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  vehicle_id: string;
  label?: null | string;
  license_plate?: null | string;
  wheelchair_accessible?: WheelchairBoarding | null;
  positions?: any[];
}

export interface VehiclePosition {
  _id?: null | string;
  revision_id?: null | string;
  agency_id: string;
  vehicle_id: string;
  timestamp?: Date;
  stop_id: null | string;
  current_stop_sequence: null | number;
  current_status: VehicleStopStatus | null;
  congestion_level: CongestionLevel | null;
  occupancy_status: OccupancyStatus | null;
  occupancy_percentage: null | number;
  latitude: null | number;
  longitude: null | number;
  bearing: null | number;
  odometer: null | number;
  speed: null | number;
  ingested_at?: Date;
  trip?: any | null;
}