// Generated by pydantic_to_ts
// Source module: models
// Generated at: 2025-10-17T23:55:01.909701



// Helper: attach Mongo/Object _id as string if desired
export type WithObjectId<T> = T & { _id: string };


export enum AlertCause {
  UNKNOWN_CAUSE = "UNKNOWN_CAUSE",
  OTHER_CAUSE = "OTHER_CAUSE",
  TECHNICAL_PROBLEM = "TECHNICAL_PROBLEM",
  STRIKE = "STRIKE",
  DEMONSTRATION = "DEMONSTRATION",
  ACCIDENT = "ACCIDENT",
  HOLIDAY = "HOLIDAY",
  WEATHER = "WEATHER",
  MAINTENANCE = "MAINTENANCE",
  CONSTRUCTION = "CONSTRUCTION",
  POLICE_ACTIVITY = "POLICE_ACTIVITY",
  MEDICAL_EMERGENCY = "MEDICAL_EMERGENCY",
}

export enum AlertEffect {
  NO_SERVICE = "NO_SERVICE",
  REDUCED_SERVICE = "REDUCED_SERVICE",
  SIGNIFICANT_DELAYS = "SIGNIFICANT_DELAYS",
  DETOUR = "DETOUR",
  ADDITIONAL_SERVICE = "ADDITIONAL_SERVICE",
  MODIFIED_SERVICE = "MODIFIED_SERVICE",
  OTHER_EFFECT = "OTHER_EFFECT",
  UNKNOWN_EFFECT = "UNKNOWN_EFFECT",
  STOP_MOVED = "STOP_MOVED",
  NO_EFFECT = "NO_EFFECT",
  ACCESSIBILITY_ISSUE = "ACCESSIBILITY_ISSUE",
}

export enum AlertSeverity {
  UNKNOWN_SEVERITY = "UNKNOWN_SEVERITY",
  INFO = "INFO",
  WARNING = "WARNING",
  SEVERE = "SEVERE",
}

export enum CalendarExceptionType {
  ADDED = "ADDED",
  REMOVED = "REMOVED",
}

export enum CongestionLevel {
  UNKNOWN_CONGESTION_LEVEL = "UNKNOWN_CONGESTION_LEVEL",
  RUNNING_SMOOTHLY = "RUNNING_SMOOTHLY",
  STOP_AND_GO = "STOP_AND_GO",
  CONGESTION = "CONGESTION",
  SEVERE_CONGESTION = "SEVERE_CONGESTION",
}

export enum Direction {
  OUTBOUND = "OUTBOUND",
  INBOUND = "INBOUND",
}

export enum LocationType {
  STOP_OR_PLATFORM = "STOP_OR_PLATFORM",
  STATION = "STATION",
  ENTRANCE_EXIT = "ENTRANCE_EXIT",
  GENERIC_NODE = "GENERIC_NODE",
  BOARDING_AREA = "BOARDING_AREA",
}

export enum OccupancyStatus {
  EMPTY = "EMPTY",
  MANY_SEATS_AVAILABLE = "MANY_SEATS_AVAILABLE",
  FEW_SEATS_AVAILABLE = "FEW_SEATS_AVAILABLE",
  STANDING_ROOM_ONLY = "STANDING_ROOM_ONLY",
  CRUSHED_STANDING_ROOM_ONLY = "CRUSHED_STANDING_ROOM_ONLY",
  FULL = "FULL",
  NOT_ACCEPTING_PASSENGERS = "NOT_ACCEPTING_PASSENGERS",
  NO_DATA_AVAILABLE = "NO_DATA_AVAILABLE",
  NOT_BOARDABLE = "NOT_BOARDABLE",
}

export enum PickupDropOff {
  REGULAR = "REGULAR",
  NO_PICKUP_OR_DROP_OFF = "NO_PICKUP_OR_DROP_OFF",
  PHONE_AGENCY = "PHONE_AGENCY",
  COORDINATE_WITH_DRIVER = "COORDINATE_WITH_DRIVER",
}

export enum RouteType {
  TRAM = "TRAM",
  SUBWAY = "SUBWAY",
  RAIL = "RAIL",
  BUS = "BUS",
  FERRY = "FERRY",
  CABLE_TRAM = "CABLE_TRAM",
  AERIAL_LIFT = "AERIAL_LIFT",
  FUNICULAR = "FUNICULAR",
  TROLLEYBUS = "TROLLEYBUS",
  MONORAIL = "MONORAIL",
}

export enum StopTimeUpdateScheduleRelationship {
  SCHEDULED = "SCHEDULED",
  SKIPPED = "SKIPPED",
  NO_DATA = "NO_DATA",
  UNSCHEDULED = "UNSCHEDULED",
}

export enum StrEnum {

}

export enum Timepoint {
  APPROXIMATE = "APPROXIMATE",
  EXACT = "EXACT",
}

export enum TripInstanceState {
  PRISTINE = "PRISTINE",
  DIRTY = "DIRTY",
  REMOVED = "REMOVED",
}

export enum VehicleStopStatus {
  INCOMING_AT = "INCOMING_AT",
  STOPPED_AT = "STOPPED_AT",
  IN_TRANSIT_TO = "IN_TRANSIT_TO",
}

export enum WheelchairBoarding {
  NO_INFO = "NO_INFO",
  ACCESSIBLE = "ACCESSIBLE",
  NOT_ACCESSIBLE = "NOT_ACCESSIBLE",
}

export interface Agency {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  source_agency_id: string;
  agency_name: string;
  agency_url: string;
  agency_timezone: string;
  agency_lang: string | null;
  agency_phone: string | null;
  agency_fare_url: string | null;
  agency_email: string | null;
}

export type AgencyWithId = WithObjectId<Agency>;

export interface Alert {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  content_hash: string;
  cause: AlertCause;
  effect: AlertEffect;
  header_text: Translation[];
  description_text: Translation[];
  url: Translation[];
  severity_level: AlertSeverity;
  active_periods: TimeRange[];
  informed_entities: EntitySelector[];
  last_seen: Date;
}

export type AlertWithId = WithObjectId<Alert>;

export interface CalendarDate {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  service_id: string;
  date: string;
  exception_type: CalendarExceptionType;
}

export type CalendarDateWithId = WithObjectId<CalendarDate>;

export interface Document {
  _id: string | null;
  revision_id: any | null;
}

export interface EntitySelector {
  agency_id: string | null;
  route_id: string | null;
  route_type: RouteType | null;
  direction_id: Direction | null;
  trip_instance: string | null;
  stop_id: string | null;
}

export interface FeedInfo {
  _id: string | null;
  revision_id: any | null;
  feed_hash: string;
  agency_id: string;
  feed_publisher_name: string | null;
  feed_publisher_url: string | null;
  feed_lang: string | null;
  feed_version: string | null;
  feed_start_date: string | null;
  feed_end_date: string | null;
}

export type FeedInfoWithId = WithObjectId<FeedInfo>;

export interface LineStringGeometry {
  type: "LineString";
  coordinates: number[][];
}

export interface PointGeometry {
  type: "Point";
  coordinates: number[];
}

export interface Route {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  route_id: string;
  route_short_name: string | null;
  route_long_name: string | null;
  route_type: RouteType;
  route_color: string | null;
  route_text_color: string | null;
}

export type RouteWithId = WithObjectId<Route>;

export interface RoutesByStop {
  _id: string | null;
  revision_id: any | null;
  stop: string;
  routes: string[];
  agency_id: string;
  stop_id: string;
}

export type RoutesByStopWithId = WithObjectId<RoutesByStop>;

export interface Shape {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  shape_id: string;
  geometry: LineStringGeometry;
  distances_traveled: number[] | null;
}

export type ShapeWithId = WithObjectId<Shape>;

export interface Stop {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  stop_id: string;
  stop_code: string | null;
  stop_name: string | null;
  stop_desc: string | null;
  location: PointGeometry | null;
  zone_id: string | null;
  stop_url: string | null;
  location_type: LocationType | null;
  parent_station: string | null;
  stop_timezone: string | null;
  wheelchair_boarding: WheelchairBoarding | null;
}

export type StopWithId = WithObjectId<Stop>;

export interface StopTime {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  trip_id: string;
  arrival_time: string;
  departure_time: string;
  stop_id: string | null;
  stop_sequence: number;
  stop_headsign: string | null;
  pickup_type: PickupDropOff | null;
  drop_off_type: PickupDropOff | null;
  timepoint: Timepoint;
  shape_dist_traveled: number | null;
}

export type StopTimeWithId = WithObjectId<StopTime>;

export interface StopTimeInstance {
  stop_id: string;
  stop_headsign: string | null;
  pickup_type: PickupDropOff | null;
  drop_off_type: PickupDropOff | null;
  timepoint: Timepoint;
  shape_dist_traveled: number | null;
  arrival_datetime: Date | null;
  departure_datetime: Date | null;
  predicted_arrival_datetime: Date | null;
  predicted_departure_datetime: Date | null;
  predicted_arrival_uncertainty: number | null;
  predicted_departure_uncertainty: number | null;
  schedule_relationship: StopTimeUpdateScheduleRelationship | null;
}

export interface TimeRange {
  start: Date | null;
  end: Date | null;
}

export interface Translation {
  language: string;
  text: string;
}

export interface Trip {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  trip_id: string;
  route_id: string;
  service_id: string;
  trip_headsign: string | null;
  trip_short_name: string | null;
  direction_id: Direction | null;
  block_id: string | null;
  shape_id: string | null;
}

export type TripWithId = WithObjectId<Trip>;

export interface TripInstance {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  trip_id: string;
  start_date: string;
  start_time: string;
  route_id: string;
  direction_id: Direction | null;
  state: TripInstanceState;
  start_datetime: Date;
  stop_times: StopTimeInstance[];
  stop_times_updated_at: Date;
  trip: string;
  route: string;
  shape: string | null;
  vehicle: string | null;
  positions: string[];
}

export type TripInstanceWithId = WithObjectId<TripInstance>;

export interface Vehicle {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  vehicle_id: string;
  label: string | null;
  license_plate: string | null;
  wheelchair_accessible: WheelchairBoarding | null;
  positions: string[];
}

export type VehicleWithId = WithObjectId<Vehicle>;

export interface VehiclePosition {
  _id: string | null;
  revision_id: any | null;
  agency_id: string;
  vehicle_id: string;
  timestamp: Date;
  stop_id: string | null;
  current_stop_sequence: number | null;
  current_status: VehicleStopStatus | null;
  congestion_level: CongestionLevel | null;
  occupancy_status: OccupancyStatus | null;
  occupancy_percentage: number | null;
  latitude: number | null;
  longitude: number | null;
  bearing: number | null;
  odometer: number | null;
  speed: number | null;
  ingested_at: Date;
  trip_instance: string | null;
}

export type VehiclePositionWithId = WithObjectId<VehiclePosition>;
