/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NtRouteImport } from './routes/nt'
import { Route as IndexRouteImport } from './routes/index'

const NtRoute = NtRouteImport.update({
  id: '/nt',
  path: '/nt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nt': typeof NtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nt': typeof NtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nt': typeof NtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nt'
  id: '__root__' | '/' | '/nt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NtRoute: typeof NtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nt': {
      id: '/nt'
      path: '/nt'
      fullPath: '/nt'
      preLoaderRoute: typeof NtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NtRoute: NtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
